import type { InputContent, InputItem, ResponseRequest } from './openai';

export interface UserMessage {
	id: string;
	role: 'user';
	text: string;
	/** Data URLs, already resized for the API. */
	images: string[];
}

export interface GeneratedImage {
	/** The image as returned by the API. */
	url: string;
	/** A lighter copy that is sent back to the API in later turns. */
	input: string;
}

export interface AssistantMessage {
	id: string;
	role: 'assistant';
	status: 'pending' | 'done' | 'failed' | 'cancelled';
	text: string;
	images: GeneratedImage[];
	startedAt: number;
	/** The background response, once created. */
	responseId?: string;
	/** What a pending response is doing. */
	phase?: 'thinking' | 'image';
	notice?: string;
	error?: {
		message: string;
		/** The API key was rejected. */
		auth?: boolean;
		/** The response is still on OpenAI's side: retrying resumes polling instead of starting over. */
		resumable?: boolean;
	};
}

export type Message = UserMessage | AssistantMessage;

export function createRequest(history: Message[], model: string, imageModel: string): ResponseRequest {
	return {
		stream: false,
		background: true,
		model,
		tools: [{ type: 'image_generation', model: imageModel }],
		input: buildInput(history)
	};
}

/**
 * The whole conversation is sent on every turn. Images generated by the assistant are included in
 * the following user message so the model can keep editing them.
 */
function buildInput(history: Message[]): InputItem[] {
	const input: InputItem[] = [{ role: 'system', content: systemPrompt(new Date()) }];
	let generated: string[] = [];

	for (const message of history) {
		if (message.role === 'assistant') {
			if (message.status !== 'done') continue;
			if (message.text) input.push({ role: 'assistant', content: message.text });
			generated.push(...message.images.map((image) => image.input));
			continue;
		}

		const content: InputContent[] = [...generated, ...message.images].map((image_url) => ({
			type: 'input_image',
			image_url
		}));
		if (message.text) content.push({ type: 'input_text', text: message.text });
		input.push({ role: 'user', content });
		generated = [];
	}

	return input;
}

function systemPrompt(date: Date) {
	const weekday = date.toLocaleDateString('en-US', { weekday: 'long' });
	const month = date.toLocaleDateString('en-US', { month: 'long' });
	const today = `${weekday}, ${date.getDate()} ${month} ${date.getFullYear()}`;

	return (
		'You are WillChat, a helpful assistant in a web chat app. ' +
		'Reply in the same language the user writes in. ' +
		'Use Markdown when it improves readability. ' +
		`Current date: ${today}. ` +
		'You can create and edit images with your image generation tool. ' +
		'Use it whenever the user asks you to create, draw, design, illustrate or modify an image. ' +
		"Earlier images in the conversation (generated by you or attached by the user) are included in the user's messages, so you can edit them; " +
		'Generated images are shown to the user automatically: never include links or Markdown images for them, just add a brief comment.'
	);
}
